
import type { College, EntranceExam } from './types';

export const colleges: College[] = [
  {
    id: 'iit-bombay',
    name: 'IIT Bombay',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'university campus',
    location: 'Mumbai, Maharashtra',
    ranking: 1,
    feeStructure: 'Approx. ₹2.2 Lakhs per year (B.Tech)',
    scholarships: ['Merit-cum-Means Scholarship', 'Inspire Scholarship'],
    courses: ['Computer Science', 'Mechanical Engineering', 'Electrical Engineering', 'Civil Engineering', 'Aerospace Engineering'],
    placements: {
      averagePackage: '₹25 LPA',
      highestPackage: '₹3.67 CPA (International)',
      topRecruiters: ['Google', 'Microsoft', 'Samsung'],
      overview: 'IIT Bombay boasts excellent placement records with students receiving offers from top global companies.',
    },
    about: 'Indian Institute of Technology Bombay is a public technical and research university located in Powai, Mumbai. It is known for its flagship 4-year, 5-year, and 2-year programmes for which the entry is through the Joint Entrance Examination – Advanced and Graduate Aptitude Test in Engineering.',
    website: 'https://www.iitb.ac.in/'
  },
  {
    id: 'iit-delhi',
    name: 'IIT Delhi',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'college building',
    location: 'New Delhi, Delhi',
    ranking: 2,
    feeStructure: 'Approx. ₹2.1 Lakhs per year (B.Tech)',
    scholarships: ['Merit-cum-Means Scholarship', 'Alumni Funded Scholarships'],
    courses: ['Textile Technology', 'Computer Science', 'Biochemical Engineering', 'Mathematics and Computing'],
    placements: {
      averagePackage: '₹24 LPA',
      highestPackage: '₹2 CPA (Domestic)',
      overview: 'IIT Delhi has a strong industry connection, leading to high placement rates in diverse sectors.',
    },
    about: 'Indian Institute of Technology Delhi is a public technical and research university located in Hauz Khas, Delhi. It is one of the oldest Indian Institutes of Technology in India.',
    website: 'https://home.iitd.ac.in/'
  },
  {
    id: 'iisc-bangalore',
    name: 'IISc Bangalore',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'research institute',
    location: 'Bengaluru, Karnataka',
    ranking: 3,
    feeStructure: 'Approx. ₹30,000 - ₹70,000 per year (Course-dependent)',
    scholarships: ['KVPY Fellowship', 'IISc Scholarships'],
    courses: ['Physics', 'Biology', 'Materials Engineering', 'Aerospace Engineering (Research)'],
    placements: {
      overview: 'IISc focuses on research and academia, with graduates often pursuing higher studies or R&D roles.',
    },
    about: 'The Indian Institute of Science is a public, deemed, research university for higher education and research in science, engineering, design, and management. It is located in Bengaluru, in the Indian state of Karnataka.',
    website: 'https://iisc.ac.in/'
  },
  {
    id: 'iit-madras',
    name: 'IIT Madras',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'tech campus',
    location: 'Chennai, Tamil Nadu',
    ranking: 4,
    feeStructure: 'Approx. ₹2.0 Lakhs per year (B.Tech)',
    scholarships: ['Central Sector Scholarship', 'State Government Scholarships'],
    courses: ['Naval Architecture', 'Ocean Engineering', 'Aerospace Engineering', 'Engineering Physics'],
    placements: {
      averagePackage: '₹22 LPA',
      overview: 'IIT Madras is known for its strong focus on innovation and entrepreneurship, reflected in its placement trends.',
    },
    about: 'Indian Institute of Technology Madras is a public technical and research university located in Chennai, Tamil Nadu and is one of the most prestigious institutes in India.',
    website: 'https://www.iitm.ac.in/'
  },
  {
    id: 'bits-pilani',
    name: 'BITS Pilani',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'private university',
    location: 'Pilani, Rajasthan',
    ranking: 10,
    feeStructure: 'Approx. ₹5.0 Lakhs per year',
    scholarships: ['Merit Scholarships', 'Merit-cum-Need Scholarships'],
    courses: ['Computer Science', 'Electronics & Communication', 'Mechanical Engineering', 'Pharmacy', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹18 LPA',
      overview: 'BITS Pilani offers excellent placements across its campuses, with a strong alumni network.',
    },
    about: 'Birla Institute of Technology & Science, Pilani is a private deemed university in Pilani, India. It focuses primarily on higher education and research in engineering and sciences.',
    website: 'https://www.bits-pilani.ac.in/'
  },
  {
    id: 'iit-kanpur',
    name: 'IIT Kanpur',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'historic campus',
    location: 'Kanpur, Uttar Pradesh',
    ranking: 5,
    feeStructure: 'Approx. ₹2.15 Lakhs per year (B.Tech)',
    scholarships: ['Various Merit and Need-based scholarships'],
    courses: ['Aerospace Engineering', 'Biological Sciences and Bioengineering', 'Chemical Engineering', 'Civil Engineering'],
    placements: {
      averagePackage: '₹23 LPA',
      overview: 'IIT Kanpur is known for its strong research focus and excellent placement opportunities.',
    },
    about: 'Indian Institute of Technology Kanpur is a public technical university located in Kanpur, Uttar Pradesh, India. It was declared to be an Institute of National Importance by the Government of India under the Institutes of Technology Act.',
    website: 'https://www.iitk.ac.in/'
  },
  {
    id: 'iit-kharagpur',
    name: 'IIT Kharagpur',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'large campus',
    location: 'Kharagpur, West Bengal',
    ranking: 6,
    feeStructure: 'Approx. ₹2.2 Lakhs per year (B.Tech)',
    scholarships: ['Merit-cum-Means, Alumni funded scholarships'],
    courses: ['Agriculture and Food Engineering', 'Architecture and Regional Planning', 'Biotechnology', 'Mining Engineering'],
    placements: {
      averagePackage: '₹20 LPA',
      overview: 'Being the oldest IIT, it has a vast alumni network and consistent placement records.',
    },
    about: 'The Indian Institute of Technology Kharagpur is a public technical university established by the government of India in Kharagpur, West Bengal, India. Established in 1951, the institute is the first of the IITs to be established and is recognised as an Institute of National Importance.',
    website: 'https://www.iitkgp.ac.in/'
  },
  {
    id: 'iit-roorkee',
    name: 'IIT Roorkee',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'heritage building',
    location: 'Roorkee, Uttarakhand',
    ranking: 7,
    feeStructure: 'Approx. ₹2.1 Lakhs per year (B.Tech)',
    scholarships: ['Institute Merit Scholarship, Inspire Scholarship'],
    courses: ['Architecture', 'Pulp and Paper Technology', 'Earthquake Engineering', 'Polymer Science and Technology'],
    placements: {
      averagePackage: '₹19 LPA',
      overview: 'IIT Roorkee offers diverse engineering programs and has a good placement record.',
    },
    about: 'Indian Institute of Technology Roorkee is a public technical university located in Roorkee, Uttarakhand, India. It is the oldest engineering institution in India, and was formerly known as Thomason College of Civil Engineering.',
    website: 'https://www.iitr.ac.in/'
  },
  {
    id: 'iit-guwahati',
    name: 'IIT Guwahati',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'scenic campus',
    location: 'Guwahati, Assam',
    ranking: 8,
    feeStructure: 'Approx. ₹2.1 Lakhs per year (B.Tech)',
    scholarships: ['Various government and private scholarships'],
    courses: ['Design', 'Biosciences and Bioengineering', 'Chemical Science and Technology', 'Electronics and Electrical Engineering'],
    placements: {
      averagePackage: '₹18 LPA',
      overview: 'IIT Guwahati is known for its beautiful campus and growing prominence in research and placements.',
    },
    about: 'Indian Institute of Technology Guwahati is a public technical university established by the Government of India, located in Amingaon area, North Guwahati city, in the state of Assam in India. It is the sixth Indian Institute of Technology established in India.',
    website: 'https://www.iitg.ac.in/'
  },
  {
    id: 'nit-trichy',
    name: 'NIT Trichy',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'engineering college',
    location: 'Tiruchirappalli, Tamil Nadu',
    ranking: 9,
    feeStructure: 'Approx. ₹1.4 Lakhs per year (B.Tech)',
    scholarships: ['Central Sector Scheme, State schemes'],
    courses: ['Metallurgical and Materials Engineering', 'Instrumentation and Control Engineering', 'Production Engineering', 'Chemical Engineering', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹12 LPA',
      overview: 'NIT Trichy is one of the top NITs with excellent academic and placement records.',
    },
    about: 'National Institute of Technology Tiruchirappalli, commonly referred to as NIT Trichy, is a public technical and research university near the city of Tiruchirappalli in Tamil Nadu, India.',
    website: 'https://www.nitt.edu/'
  },
  {
    id: 'jadavpur-university',
    name: 'Jadavpur University',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'old university',
    location: 'Kolkata, West Bengal',
    ranking: 11,
    feeStructure: 'Approx. ₹10,000 - ₹30,000 per year (Highly Subsidized)',
    scholarships: ['State Government scholarships, University specific aids'],
    courses: ['Power Engineering', 'Construction Engineering', 'Printing Engineering', 'Information Technology', 'Masters in Computer Applications', 'Bachelor of Computer Applications'],
    placements: {
      averagePackage: '₹10 LPA',
      overview: 'Jadavpur University is known for its strong engineering programs and affordable education with good placements.',
    },
    about: 'Jadavpur University is a public technical university located in Jadavpur, Kolkata, West Bengal, India. It has a long tradition of providing high-quality education at nominal costs.',
    website: 'http://www.jaduniv.edu.in/'
  },
  {
    id: 'vit-vellore',
    name: 'VIT Vellore',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'modern campus',
    location: 'Vellore, Tamil Nadu',
    ranking: 12,
    feeStructure: 'Approx. ₹1.98 Lakhs per year (B.Tech Group A) to ₹3.95 Lakhs (B.Tech Group B)',
    scholarships: ['GV School Development Programme (GVSDP)', 'STARS scheme'],
    courses: ['Information Technology', 'Computer Science and Engineering (Specialization in AI)', 'Electronics and Communication Engineering', 'Mechanical Engineering', 'Masters in Computer Applications', 'Bachelor of Computer Applications'],
    placements: {
      averagePackage: '₹9 LPA',
      highestPackage: '₹1.02 CPA',
      topRecruiters: ['Microsoft', 'Amazon', 'Deloitte'],
      overview: 'VIT is known for its large student intake and good placement opportunities in IT and core sectors.',
    },
    about: 'Vellore Institute of Technology (VIT) is a private deemed university located in Vellore, Tamil Nadu, India. It has campuses in Vellore, Chennai, Amaravati and Bhopal.',
    website: 'https://vit.ac.in/'
  },
  {
    id: 'nit-surathkal',
    name: 'NIT Surathkal',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'coastal campus',
    location: 'Mangalore, Karnataka',
    ranking: 13,
    feeStructure: 'Approx. ₹1.5 Lakhs per year (B.Tech)',
    scholarships: ['Various central and state government scholarships'],
    courses: ['Mining Engineering', 'Marine Structures', 'Computational and Data Science', 'Civil Engineering', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹11 LPA',
      overview: 'NITK Surathkal is a premier NIT with a beautiful coastal campus and strong placement records.',
    },
    about: 'National Institute of Technology Karnataka, also known as NITK Surathkal, formerly Karnataka Regional Engineering College, is a public technical university at Surathkal, Mangalore.',
    website: 'https://www.nitk.ac.in/'
  },
  {
    id: 'anna-university',
    name: 'Anna University',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'state university',
    location: 'Chennai, Tamil Nadu',
    ranking: 14,
    feeStructure: 'Approx. ₹50,000 - ₹60,000 per year (Govt. Quota)',
    scholarships: ['BC/MBC Scholarships, SC/ST Scholarships'],
    courses: ['Geo-Informatics', 'Automobile Engineering', 'Manufacturing Engineering', 'Electronics and Instrumentation Engineering', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹7 LPA',
      overview: 'Anna University is a large technical university with many affiliated colleges. Placements vary by college.',
    },
    about: 'Anna University is a public state university located in Chennai, Tamil Nadu, India. The main university campus is located in Guindy, Chennai.',
    website: 'https://www.annauniv.edu/'
  },
  {
    id: 'iit-hyderabad',
    name: 'IIT Hyderabad',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'new iit campus',
    location: 'Hyderabad, Telangana',
    ranking: 15,
    feeStructure: 'Approx. ₹2.2 Lakhs per year (B.Tech)',
    scholarships: ['Institute SC/ST Scholarship, MCM scholarship'],
    courses: ['Artificial Intelligence', 'Engineering Science', 'Biomedical Engineering', 'Materials Science and Metallurgical Engineering'],
    placements: {
      averagePackage: '₹20 LPA',
      overview: 'IIT Hyderabad is one of the newer IITs but has quickly established a reputation for quality education and research.',
    },
    about: 'Indian Institute of Technology Hyderabad is a public technical university located in Sangareddy district, Telangana, India. IITH is known for its academic strength, research, publications and proximity to IT and industrial hubs.',
    website: 'https://www.iith.ac.in/'
  },
  {
    id: 'nit-warangal',
    name: 'NIT Warangal',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'historic nit',
    location: 'Warangal, Telangana',
    ranking: 16,
    feeStructure: 'Approx. ₹1.3 Lakhs per year (B.Tech)',
    scholarships: ['Scholarships for SC/ST/OBC/Minority students'],
    courses: ['Biotechnology', 'Chemical Engineering', 'Civil Engineering', 'Computer Science and Engineering', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹10 LPA',
      overview: 'NIT Warangal is one of the oldest and most reputed NITs in India.',
    },
    about: 'National Institute of Technology, Warangal is a public technical and research university located in Warangal, India. It is recognised as an Institute of National Importance by the Government of India.',
    website: 'https://www.nitw.ac.in/'
  },
  {
    id: 'iit-indore',
    name: 'IIT Indore',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'modern architecture',
    location: 'Indore, Madhya Pradesh',
    ranking: 17,
    feeStructure: 'Approx. ₹2.3 Lakhs per year (B.Tech)',
    scholarships: ['Merit-cum-Means Scholarship, Central Sector Scholarships'],
    courses: ['Space Sciences and Engineering', 'Metallurgy Engineering and Materials Science', 'Electrical Engineering', 'Computer Science and Engineering'],
    placements: {
      averagePackage: '₹18 LPA',
      overview: 'IIT Indore has shown rapid growth in academic and research activities, leading to good placements.',
    },
    about: 'Indian Institute of Technology Indore, located in Indore, is an institute of national importance established by the Government of India in 2009.',
    website: 'https://www.iiti.ac.in/'
  },
  {
    id: 'iit-bhu',
    name: 'IIT (BHU) Varanasi',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'historic university',
    location: 'Varanasi, Uttar Pradesh',
    ranking: 18,
    feeStructure: 'Approx. ₹2.2 Lakhs per year (B.Tech)',
    scholarships: ['Various internal and external scholarships'],
    courses: ['Pharmaceutical Engineering & Technology', 'Ceramic Engineering', 'Mining Engineering', 'Biochemical Engineering'],
    placements: {
      averagePackage: '₹17 LPA',
      overview: 'IIT (BHU) has a long history and offers a wide range of engineering programs.',
    },
    about: 'The Indian Institute of Technology (BHU) Varanasi is a public technical university located in Varanasi, Uttar Pradesh, India. Founded in 1919 as the Banaras Engineering College, it became an IIT in 2012.',
    website: 'https://iitbhu.ac.in/'
  },
  {
    id: 'ict-mumbai',
    name: 'ICT Mumbai',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'chemical technology',
    location: 'Mumbai, Maharashtra',
    ranking: 19,
    feeStructure: 'Approx. ₹85,000 per year (B.Tech)',
    scholarships: ['Merit based, Industry sponsored scholarships'],
    courses: ['Chemical Engineering', 'Dyestuff Technology', 'Food Engineering and Technology', 'Pharmaceuticals Chemistry and Technology'],
    placements: {
      averagePackage: '₹8 LPA',
      overview: 'Institute of Chemical Technology is a premier institute for chemical engineering and technology.',
    },
    about: 'Institute of Chemical Technology is a public deemed university in Mumbai, India. The institute also has campuses at Jalna, Marathwada and Bhubaneswar, Odisha. It is focused on training and research in fields of chemical engineering, chemical technology, and pharmacy.',
    website: 'https://www.ictmumbai.edu.in/'
  },
  {
    id: 'iit-ropar',
    name: 'IIT Ropar',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'new infrastructure',
    location: 'Rupnagar, Punjab',
    ranking: 20,
    feeStructure: 'Approx. ₹2.1 Lakhs per year (B.Tech)',
    scholarships: ['MCM Scholarship, Institute Free Studentship'],
    courses: ['Biomedical Engineering', 'Mathematics and Computing', 'Chemical Engineering', 'Mechanical Engineering'],
    placements: {
      averagePackage: '₹16 LPA',
      overview: 'IIT Ropar is among the newer IITs showing strong growth in placements and research output.',
    },
    about: 'Indian Institute of Technology Ropar is a public technical university located in Rupnagar, Punjab, India. It is one of the eight newer Indian Institutes of Technology established by the Ministry of Human Resource Development, Government of India.',
    website: 'https://www.iitrpr.ac.in/'
  },
  {
    id: 'iit-patna',
    name: 'IIT Patna',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'developing campus',
    location: 'Patna, Bihar',
    ranking: 21,
    feeStructure: 'Approx. ₹2.2 Lakhs per year (B.Tech)',
    scholarships: ['Various government scholarships'],
    courses: ['AI and Data Science', 'Civil and Environmental Engineering', 'Computer Science', 'Electrical Engineering'],
    placements: {
      averagePackage: '₹15 LPA',
      overview: 'IIT Patna is steadily improving its academic and placement performance.',
    },
    about: 'Indian Institute of Technology Patna is a public technical university located in Bihta, Patna, India. It is recognized as an Institute of National Importance by the Government of India.',
    website: 'https://www.iitp.ac.in/'
  },
  {
    id: 'iiest-shibpur',
    name: 'IIEST Shibpur',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'historic engineering',
    location: 'Howrah, West Bengal',
    ranking: 22,
    feeStructure: 'Approx. ₹1.5 Lakhs per year (B.Tech)',
    scholarships: ['Merit-cum-Means, Institute specific'],
    courses: ['Aerospace Engineering', 'Civil Engineering', 'Computer Science and Technology', 'Mining Engineering'],
    placements: {
      averagePackage: '₹9 LPA',
      overview: 'Indian Institute of Engineering Science and Technology, Shibpur has a long legacy in engineering education.',
    },
    about: 'Indian Institute of Engineering Science and Technology, Shibpur is a public technical and research university located at Shibpur, Howrah district, West Bengal. It is recognised as an Institute of National Importance under MHRD by the Government of India.',
    website: 'https://www.iiests.ac.in/'
  },
  {
    id: 'nit-rourkela',
    name: 'NIT Rourkela',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'industrial area campus',
    location: 'Rourkela, Odisha',
    ranking: 23,
    feeStructure: 'Approx. ₹1.6 Lakhs per year (B.Tech)',
    scholarships: ['Merit and need-based scholarships'],
    courses: ['Ceramic Engineering', 'Food Process Engineering', 'Industrial Design', 'Biomedical Engineering', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹10 LPA',
      overview: 'NIT Rourkela offers a wide range of engineering disciplines and has good industry connections.',
    },
    about: 'National Institute of Technology Rourkela, formerly Regional Engineering College Rourkela, is a publicly funded institute of higher learning for engineering, science and technology located in the steel city of Rourkela, Odisha, India.',
    website: 'https://www.nitrkl.ac.in/'
  },
  {
    id: 'iit-gandhinagar',
    name: 'IIT Gandhinagar',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'sustainable campus',
    location: 'Gandhinagar, Gujarat',
    ranking: 24,
    feeStructure: 'Approx. ₹2.3 Lakhs per year (B.Tech)',
    scholarships: ['Financial aid provided by the institute'],
    courses: ['Society and Culture', 'Earth Sciences', 'Electrical Engineering', 'Mechanical Engineering'],
    placements: {
      averagePackage: '₹14 LPA',
      overview: 'IIT Gandhinagar focuses on interdisciplinary learning and has a growing placement record.',
    },
    about: 'Indian Institute of Technology Gandhinagar is a public technical university located in Gandhinagar, Gujarat, India. It has been declared to be an Institute of National Importance by the Government of India.',
    website: 'https://iitgn.ac.in/'
  },
  {
    id: 'thapar-patiala',
    name: 'Thapar Institute (Patiala)',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'private engineering college',
    location: 'Patiala, Punjab',
    ranking: 25,
    feeStructure: 'Approx. ₹4.5 Lakhs per year (B.E./B.Tech)',
    scholarships: ['Merit based scholarships'],
    courses: ['Biotechnology', 'Civil Engineering (with specialization)', 'Computer Science and Business Systems', 'Mechatronics', 'Masters in Computer Applications', 'Bachelor of Computer Applications'],
    placements: {
      averagePackage: '₹10 LPA',
      overview: 'Thapar Institute of Engineering and Technology is a well-regarded private engineering institution.',
    },
    about: 'Thapar Institute of Engineering and Technology is a private deemed-to-be-university, in Patiala, Punjab, India. It was founded in 1956 by Karam Chand Thapar.',
    website: 'https://www.thapar.edu/'
  },
  {
    id: 'amrita-coimbatore',
    name: 'Amrita Vishwa Vidyapeetham (Coimbatore)',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'spiritual campus',
    location: 'Coimbatore, Tamil Nadu',
    ranking: 26,
    feeStructure: 'Approx. ₹3.5 Lakhs per year (B.Tech)',
    scholarships: ['Amrita Entrance Examination based scholarships'],
    courses: ['Aerospace Engineering', 'Automation and Robotics Engineering', 'Cyber Security', 'Electronics and Computer Engineering', 'Masters in Computer Applications', 'Bachelor of Computer Applications'],
    placements: {
      averagePackage: '₹7.5 LPA',
      overview: 'Amrita University has multiple campuses and offers a wide range of programs with decent placements.',
    },
    about: 'Amrita Vishwa Vidyapeetham is a private deemed university based in Coimbatore, Tamil Nadu, India. It is a multi-campus, multi-disciplinary teaching and research university.',
    website: 'https://www.amrita.edu/'
  },
  {
    id: 'srm-chennai',
    name: 'SRM IST (Chennai)',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'large private campus',
    location: 'Chennai, Tamil Nadu',
    ranking: 27,
    feeStructure: 'Approx. ₹2.5 - ₹4.5 Lakhs per year (B.Tech depending on specialization)',
    scholarships: ['SRMJEEE Rank based, Socio-economic scholarships'],
    courses: ['Automobile Engineering with specialization in Electric Vehicles', 'Nanotechnology', 'Genetic Engineering', 'Software Engineering', 'Masters in Computer Applications', 'Bachelor of Computer Applications'],
    placements: {
      averagePackage: '₹6 LPA',
      overview: 'SRM Institute of Science and Technology is a large private university with a high volume of placements.',
    },
    about: 'SRM Institute of Science and Technology, is a private deemed university located in Kattankulathur, Chengalpattu, Tamil Nadu, India, near Chennai. It was founded in 1985 as SRM Engineering College in Kattankulathur.',
    website: 'https://www.srmist.edu.in/'
  },
  {
    id: 'nit-calicut',
    name: 'NIT Calicut',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'kerala campus',
    location: 'Kozhikode, Kerala',
    ranking: 28,
    feeStructure: 'Approx. ₹1.4 Lakhs per year (B.Tech)',
    scholarships: ['National and State level scholarships'],
    courses: ['Architecture', 'Engineering Physics', 'Materials Science and Engineering', 'Production Engineering', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹9.5 LPA',
      overview: 'NIT Calicut is a prominent engineering college in Kerala with good academic standards.',
    },
    about: 'National Institute of Technology Calicut, formerly Regional Engineering College Calicut, is a public technical university and an institute of national importance governed by the NIT Act passed by the Parliament of India.',
    website: 'https://nitc.ac.in/'
  },
  {
    id: 'iit-dhanbad',
    name: 'IIT (ISM) Dhanbad',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'mining institute',
    location: 'Dhanbad, Jharkhand',
    ranking: 29,
    feeStructure: 'Approx. ₹2.2 Lakhs per year (B.Tech)',
    scholarships: ['Merit-cum-Means, Alumni scholarships'],
    courses: ['Mining Engineering', 'Petroleum Engineering', 'Environmental Science and Engineering', 'Applied Geology'],
    placements: {
      averagePackage: '₹16 LPA',
      overview: 'Formerly Indian School of Mines, it excels in mining and earth sciences related engineering fields.',
    },
    about: 'Indian Institute of Technology (Indian School of Mines), Dhanbad is a public technical university located in Dhanbad, India. It has main focus on Mining and Mineral Engineering.',
    website: 'https://www.iitism.ac.in/'
  },
  {
    id: 'manipal-mit',
    name: 'Manipal Institute of Technology',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'international campus feel',
    location: 'Manipal, Karnataka',
    ranking: 30,
    feeStructure: 'Approx. ₹4.0 Lakhs per year (B.Tech)',
    scholarships: ['Merit-based scholarships for top rankers in MET'],
    courses: ['Data Science and Engineering', 'Mechatronics Engineering', 'Aeronautical Engineering', 'Biomedical Engineering', 'Masters in Computer Applications', 'Bachelor of Computer Applications'],
    placements: {
      averagePackage: '₹8 LPA',
      overview: 'MIT Manipal is a well-known private engineering college with a diverse student population.',
    },
    about: 'Manipal Institute of Technology is a private constituent institution of Manipal Academy of Higher Education that specializes in engineering. MIT contains 17 academic departments and awards undergraduate, graduate and post graduate degrees.',
    website: 'https://manipal.edu/mit.html'
  },
  {
    id: 'coep-pune',
    name: 'COEP Technological University (Pune)',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'historic pune college',
    location: 'Pune, Maharashtra',
    ranking: 31,
    feeStructure: 'Approx. ₹90,000 per year (B.Tech)',
    scholarships: ['Government of Maharashtra scholarships'],
    courses: ['Metallurgy and Material Technology', 'Instrumentation and Control', 'Production Engineering (Sandwich)', 'Robotics and Artificial Intelligence', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹9 LPA',
      overview: 'College of Engineering, Pune is one of the oldest engineering colleges in Asia with a strong reputation.',
    },
    about: 'COEP Technological University, formerly College of Engineering, Pune, is a unitary public university of the government of Maharashtra, situated in Pune, Maharashtra, India. Established in 1854, it is one of the oldest engineering colleges in Asia.',
    website: 'https://www.coep.org.in/'
  },
  {
    id: 'iiit-hyderabad',
    name: 'IIIT Hyderabad',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'it focused institute',
    location: 'Hyderabad, Telangana',
    ranking: 32,
    feeStructure: 'Approx. ₹3.6 Lakhs per year',
    scholarships: ['Pratibha scholarship (State govt.), Financial assistance schemes'],
    courses: ['Computer Science and Engineering', 'Electronics and Communication Engineering', 'Computational Linguistics', 'Computer Science and Human Sciences', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹30 LPA (CSE)',
      overview: 'International Institute of Information Technology, Hyderabad is renowned for its strong focus on CS and IT related research and education.',
    },
    about: 'International Institute of Information Technology, Hyderabad is an autonomous university, founded as a not-for-profit public private partnership in 1998. It is one of the top Computer Science institutes in the country.',
    website: 'https://www.iiit.ac.in/'
  },
  {
    id: 'nit-kurukshetra',
    name: 'NIT Kurukshetra',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'north india nit',
    location: 'Kurukshetra, Haryana',
    ranking: 33,
    feeStructure: 'Approx. ₹1.5 Lakhs per year (B.Tech)',
    scholarships: ['Central and State Government schemes'],
    courses: ['Industrial Engineering & Management', 'Information Technology', 'Production and Industrial Engineering', 'Electrical Engineering', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹9 LPA',
      overview: 'NIT Kurukshetra is a well-established NIT in North India with good placements.',
    },
    about: 'National Institute of Technology, Kurukshetra is a public technical and research university located in Kurukshetra, Haryana, India. It is recognized as an Institute of National Importance by the Indian government.',
    website: 'https://nitkkr.ac.in/'
  },
  {
    id: 'mnnit-allahabad',
    name: 'MNNIT Allahabad',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'up nit campus',
    location: 'Prayagraj, Uttar Pradesh',
    ranking: 34,
    feeStructure: 'Approx. ₹1.6 Lakhs per year (B.Tech)',
    scholarships: ['Various government scholarships for reserved categories'],
    courses: ['Biotechnology', 'Chemical Engineering', 'Civil Engineering', 'Computer Science and Engineering', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹11 LPA',
      overview: 'Motilal Nehru National Institute of Technology Allahabad is a prominent NIT with strong academic programs.',
    },
    about: 'Motilal Nehru National Institute of Technology Allahabad, formerly Motilal Nehru Regional Engineering College, is a public technical university located in Prayagraj, Uttar Pradesh, India.',
    website: 'http://www.mnnit.ac.in/'
  },
  {
    id: 'svnit-surat',
    name: 'SVNIT Surat',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'gujarat nit campus',
    location: 'Surat, Gujarat',
    ranking: 35,
    feeStructure: 'Approx. ₹1.5 Lakhs per year (B.Tech)',
    scholarships: ['Scholarships for meritorious and economically weaker students'],
    courses: ['Chemical Engineering', 'Civil Engineering', 'Computer Engineering', 'Electrical Engineering', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹8.5 LPA',
      overview: 'Sardar Vallabhbhai National Institute of Technology, Surat is a respected NIT in Western India.',
    },
    about: 'Sardar Vallabhbhai National Institute of Technology, Surat, commonly known as National Institute of Technology, Surat, is an institute of national importance imparting higher education in engineering and technology.',
    website: 'https://www.svnit.ac.in/'
  },
  {
    id: 'iiit-bangalore',
    name: 'IIIT Bangalore',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'tech hub institute',
    location: 'Bengaluru, Karnataka',
    ranking: 36,
    feeStructure: 'Approx. ₹5 Lakhs per year (Integrated M.Tech)',
    scholarships: ['Merit-based scholarships, Industry sponsored scholarships'],
    courses: ['Integrated M.Tech in CSE', 'Integrated M.Tech in ECE', 'Master of Science by Research', 'PhD Programs'],
    placements: {
      averagePackage: '₹25 LPA',
      overview: 'International Institute of Information Technology Bangalore is known for its postgraduate programs and strong industry ties.',
    },
    about: 'International Institute of Information Technology Bangalore is a private technology university located in Bangalore, India. The university is a DNB and Deemed University, and is promoted by the Government of Karnataka and the IT industry.',
    website: 'https://www.iiitb.ac.in/'
  },
  {
    id: 'nit-nagpur',
    name: 'VNIT Nagpur',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'maharashtra nit campus',
    location: 'Nagpur, Maharashtra',
    ranking: 37,
    feeStructure: 'Approx. ₹1.5 Lakhs per year (B.Tech)',
    scholarships: ['Central and State scholarships'],
    courses: ['Mining Engineering', 'Metallurgical and Materials Engineering', 'Architecture', 'Chemical Engineering', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹8 LPA',
      overview: 'Visvesvaraya National Institute of Technology, Nagpur is a well-established NIT.',
    },
    about: 'Visvesvaraya National Institute of Technology Nagpur, also referred to as NIT Nagpur, is a public technical university located in the central Indian city of Nagpur, Maharashtra.',
    website: 'https://vnit.ac.in/'
  },
  {
    id: 'iit-ropar-alt', // Using alt id as iit-ropar already exists, adjust if needed
    name: 'IIT Ropar (Alternate Entry)', // Placeholder name, adjust as needed
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'punjab iit campus',
    location: 'Rupnagar, Punjab',
    ranking: 38, // Adjust ranking
    feeStructure: 'Approx. ₹2.1 Lakhs per year (B.Tech)',
    scholarships: ['MCM Scholarship, Institute Free Studentship'],
    courses: ['Civil Engineering', 'Electrical Engineering (VLSI Design and Technology)', 'Computer Science and Engineering (AI)', 'Mechanical Engineering (Manufacturing)'],
    placements: {
      averagePackage: '₹16.5 LPA', // Slightly different data
      overview: 'IIT Ropar offers specialized tracks and shows consistent growth in industry collaborations.',
    },
    about: 'Indian Institute of Technology Ropar, a newer IIT, is rapidly establishing itself with innovative programs and research focus. It is located in Punjab, India.',
    website: 'https://www.iitrpr.ac.in/'
  },
  {
    id: 'pec-chandigarh',
    name: 'PEC Chandigarh',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'chandigarh engineering',
    location: 'Chandigarh',
    ranking: 39,
    feeStructure: 'Approx. ₹2 Lakhs per year (B.E.)',
    scholarships: ['Merit scholarships, Post-matric scholarships'],
    courses: ['Aerospace Engineering', 'Materials and Metallurgical Engineering', 'Production and Industrial Engineering', 'Civil Engineering', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹10.5 LPA',
      overview: 'Punjab Engineering College (Deemed to be University), Chandigarh, has a rich history and strong alumni network.',
    },
    about: 'Punjab Engineering College is a public technical institution in Chandigarh, India. Founded in 1921, it is one of the oldest engineering institutes in the country.',
    website: 'https://pec.ac.in/'
  },
  {
    id: 'iiit-allahabad',
    name: 'IIIT Allahabad',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'information technology institute',
    location: 'Prayagraj, Uttar Pradesh',
    ranking: 40,
    feeStructure: 'Approx. ₹1.8 Lakhs per year (B.Tech)',
    scholarships: ['Various state and central government scholarships'],
    courses: ['Information Technology', 'Electronics and Communication Engineering', 'IT (Business Informatics)', 'Robotics and Automation', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹20 LPA',
      overview: 'Indian Institute of Information Technology, Allahabad focuses on IT and related areas with excellent placement records.',
    },
    about: 'Indian Institute of Information Technology, Allahabad is a public university located in Jhalwa, Prayagraj district, in Uttar Pradesh state in India. It is one of the twenty-five IIITs listed by the MHRD.',
    website: 'https://www.iiita.ac.in/'
  },
  {
    id: 'nit-jalandhar',
    name: 'NIT Jalandhar',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'punjab nit',
    location: 'Jalandhar, Punjab',
    ranking: 41,
    feeStructure: 'Approx. ₹1.7 Lakhs per year (B.Tech)',
    scholarships: ['Scholarship schemes for various categories'],
    courses: ['Textile Technology', 'Industrial & Production Engineering', 'Instrumentation & Control Engineering', 'Bio Technology', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹8 LPA',
      overview: 'Dr. B. R. Ambedkar National Institute of Technology Jalandhar is a public engineering university located in Jalandhar, Punjab, India.',
    },
    about: 'Dr. B. R. Ambedkar National Institute of Technology Jalandhar, formerly Regional Engineering College Jalandhar, is a public technical university located in Jalandhar, Punjab, India.',
    website: 'https://www.nitj.ac.in/'
  },
  {
    id: 'daiict-gandhinagar',
    name: 'DAIICT Gandhinagar',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'ict university',
    location: 'Gandhinagar, Gujarat',
    ranking: 42,
    feeStructure: 'Approx. ₹1.8 Lakhs per year (B.Tech ICT)',
    scholarships: ['Merit and Merit-cum-Means scholarships'],
    courses: ['Information and Communication Technology (ICT)', 'ICT with minor in Computational Science', 'Mathematics and Computing', 'Electronics and VLSI Design', 'Masters in Computer Applications', 'Bachelor of Computer Applications'],
    placements: {
      averagePackage: '₹15 LPA',
      overview: 'Dhirubhai Ambani Institute of Information and Communication Technology is known for its specialized programs in ICT.',
    },
    about: 'Dhirubhai Ambani Institute of Information and Communication Technology is a private self-financed university located in Gandhinagar, Gujarat, India. It is named after the Indian entrepreneur and philanthropist Dhirubhai Ambani.',
    website: 'https://www.daiict.ac.in/'
  },
  {
    id: 'nit-silchar',
    name: 'NIT Silchar',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'assam nit',
    location: 'Silchar, Assam',
    ranking: 43,
    feeStructure: 'Approx. ₹1.5 Lakhs per year (B.Tech)',
    scholarships: ['Various scholarships for eligible students'],
    courses: ['Civil Engineering', 'Computer Science and Engineering', 'Electronics and Communication Engineering', 'Mechanical Engineering', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹7.5 LPA',
      overview: 'National Institute of Technology Silchar is an Institute of National Importance located in Silchar, Assam, India.',
    },
    about: 'National Institute of Technology Silchar is one of the 31 NITs of India and was established in 1967 as a Regional Engineering College in Silchar. In 2002, it was upgraded to the status of National Institute of Technology.',
    website: 'http://www.nits.ac.in/'
  },
  {
    id: 'nit-jaipur',
    name: 'MNIT Jaipur',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'rajasthan nit',
    location: 'Jaipur, Rajasthan',
    ranking: 44,
    feeStructure: 'Approx. ₹1.6 Lakhs per year (B.Tech)',
    scholarships: ['Government and Institute scholarships'],
    courses: ['Architecture', 'Chemical Engineering', 'Civil Engineering', 'Computer Science and Engineering', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹10 LPA',
      overview: 'Malaviya National Institute of Technology Jaipur is a public technical university located in Jaipur, India with a focus on science, engineering and management.',
    },
    about: 'Malaviya National Institute of Technology Jaipur is a public technical university located in Jaipur, India. Established in 1963 as Malaviya Regional Engineering College Jaipur, it became a National Institute of Technology in 2002.',
    website: 'https://www.mnit.ac.in/'
  },
  {
    id: 'bits-hyderabad',
    name: 'BITS Hyderabad',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'bits campus south',
    location: 'Hyderabad, Telangana',
    ranking: 45,
    feeStructure: 'Approx. ₹5.0 Lakhs per year',
    scholarships: ['Merit Scholarships, Merit-cum-Need Scholarships based on BITSAT score'],
    courses: ['Chemical Engineering', 'Civil Engineering', 'Computer Science', 'Electronics & Instrumentation', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹17 LPA',
      overview: 'BITS Pilani, Hyderabad Campus offers similar quality education and placement opportunities as the Pilani campus.',
    },
    about: 'Birla Institute of Technology & Science, Pilani – Hyderabad Campus is a private deemed university campus located in Hyderabad, Telangana, India. It is one of the four constituent campuses of BITS Pilani.',
    website: 'https://www.bits-pilani.ac.in/hyderabad/'
  },
  {
    id: 'nit-bhopal',
    name: 'MANIT Bhopal',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'mp nit campus',
    location: 'Bhopal, Madhya Pradesh',
    ranking: 46,
    feeStructure: 'Approx. ₹1.5 Lakhs per year (B.Tech)',
    scholarships: ['Scholarships based on merit and category'],
    courses: ['Planning', 'Chemical Engineering', 'Computer Science and Engineering', 'Electrical Engineering', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹8 LPA',
      overview: 'Maulana Azad National Institute of Technology Bhopal is an Institute of National Importance under Ministry of Education, Government of India.',
    },
    about: 'Maulana Azad National Institute of Technology Bhopal, also known as NIT Bhopal, is a public technical university located in Bhopal, Madhya Pradesh, India. It is part of the group of NITs.',
    website: 'http://www.manit.ac.in/'
  },
  {
    id: 'iiit-gwalior',
    name: 'IIITM Gwalior',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'management tech institute',
    location: 'Gwalior, Madhya Pradesh',
    ranking: 47,
    feeStructure: 'Approx. ₹1.7 Lakhs per year (IPG - M.Tech)',
    scholarships: ['Financial assistance schemes'],
    courses: ['Integrated B.Tech (IT) and MBA', 'Integrated B.Tech (IT) and M.Tech (IT)', 'PhD Programs', 'Management Development Programs', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹14 LPA',
      overview: 'Indian Institute of Information Technology and Management Gwalior offers unique integrated programs in IT and Management.',
    },
    about: 'Atal Bihari Vajpayee Indian Institute of Information Technology and Management Gwalior, commonly known as the Indian Institute of Information Technology and Management Gwalior, is an autonomous institute set up by Ministry of Human Resource Development, Government of India.',
    website: 'https://www.iiitm.ac.in/'
  },
  {
    id: 'nit-durgapur',
    name: 'NIT Durgapur',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'west bengal nit',
    location: 'Durgapur, West Bengal',
    ranking: 48,
    feeStructure: 'Approx. ₹1.6 Lakhs per year (B.Tech)',
    scholarships: ['Multiple scholarship options available'],
    courses: ['Biotechnology', 'Chemical Engineering', 'Computer Science and Engineering', 'Metallurgical and Materials Engineering', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹7 LPA',
      overview: 'National Institute of Technology Durgapur is an institute of national importance in Durgapur, West Bengal, India.',
    },
    about: 'National Institute of Technology Durgapur, formerly Regional Engineering College, Durgapur, is a public technical university in the city of Durgapur in West Bengal, India. It is among the oldest NITs.',
    website: 'https://nitdgp.ac.in/'
  },
  {
    id: 'dtu-delhi',
    name: 'DTU Delhi',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'delhi tech university',
    location: 'New Delhi, Delhi',
    ranking: 49,
    feeStructure: 'Approx. ₹2.1 Lakhs per year (B.Tech)',
    scholarships: ['Merit cum Means EWS Scholarship, various private scholarships'],
    courses: ['Automotive Engineering', 'Engineering Physics', 'Software Engineering', 'Mathematics and Computing', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹13 LPA',
      overview: 'Delhi Technological University, formerly Delhi College of Engineering, is a state university in New Delhi, India.',
    },
    about: 'Delhi Technological University, formerly known as the Delhi College of Engineering, is a state university in New Delhi, India. It was established in 1941 as Delhi Polytechnic.',
    website: 'http://dtu.ac.in/'
  },
  {
    id: 'nit-patna',
    name: 'NIT Patna',
    logoUrl: 'https://placehold.co/100x100.png',
    campusPhotoUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'bihar nit campus',
    location: 'Patna, Bihar',
    ranking: 50,
    feeStructure: 'Approx. ₹1.6 Lakhs per year (B.Tech)',
    scholarships: ['Post Matric Scholarships, Bihar Student Credit Card Scheme'],
    courses: ['Architecture', 'Civil Engineering with specialization in Construction Technology', 'Computer Science & Engineering with specialization in Data Science', 'Electrical Engineering with specialization in Power System Engineering', 'Masters in Computer Applications'],
    placements: {
      averagePackage: '₹7.5 LPA',
      overview: 'National Institute of Technology Patna is the 18th National Institute of Technology created by the Ministry of H.R.D. Government of India after rechristening the erstwhile Bihar College of Engineering Patna.',
    },
    about: 'National Institute of Technology Patna is a public technical university located in Patna, Bihar, India. It was renamed from Bihar College of Engineering Patna in 2004. It is an Institute of National Importance.',
    website: 'https://www.nitp.ac.in/'
  }
];

export const entranceExams: EntranceExam[] = [
  {
    id: 'jee-advanced',
    name: 'JEE Advanced 2024',
    date: 'Results: June 9, 2024',
    description: 'For admission to undergraduate courses leading to a Bachelor\'s, Integrated Master\'s or Bachelor-Master Dual Degree in Engineering, Sciences, or Architecture in the IITs.',
    bannerImageUrl: 'https://placehold.co/800x300.png',
    dataAiHint: 'exam hall students',
    relevantColleges: ['iit-bombay', 'iit-delhi', 'iit-madras', 'iit-kanpur', 'iit-kharagpur', 'iit-roorkee', 'iit-guwahati', 'iit-hyderabad', 'iit-indore', 'iit-bhu', 'iit-ropar', 'iit-patna', 'iit-gandhinagar', 'iit-dhanbad']
  },
  {
    id: 'bitsat',
    name: 'BITSAT 2024',
    date: 'Session 2: June 24-28, 2024',
    description: 'BITS Admission Test for integrated first-degree programmes of BITS Pilani campuses in Pilani, Goa, and Hyderabad.',
    bannerImageUrl: 'https://placehold.co/800x300.png',
    dataAiHint: 'university entrance exam',
    relevantColleges: ['bits-pilani', 'bits-hyderabad']
  },
  {
    id: 'jee-main',
    name: 'JEE Main 2025',
    date: 'Session 1: Jan 2025 (Tentative)',
    description: 'For admission to NITs, IIITs, and other Centrally Funded Technical Institutions (CFTIs), and as eligibility for JEE Advanced.',
    bannerImageUrl: 'https://placehold.co/800x300.png',
    dataAiHint: 'students writing exam',
    relevantColleges: ['nit-trichy', 'nit-surathkal', 'nit-warangal', 'nit-calicut', 'nit-rourkela', 'mnnit-allahabad', 'svnit-surat', 'nit-kurukshetra', 'nit-jaipur', 'nit-bhopal', 'nit-nagpur', 'nit-jalandhar', 'nit-silchar', 'nit-durgapur', 'nit-patna', 'iiit-hyderabad', 'iiit-bangalore', 'iiit-allahabad', 'iiit-gwalior', 'pec-chandigarh', 'dtu-delhi', 'iiest-shibpur']
  },
  {
    id: 'gate',
    name: 'GATE 2025',
    date: 'Applications: Aug 2024 (Tentative)',
    description: 'Graduate Aptitude Test in Engineering for Master\'s programs and PSU recruitment.',
    bannerImageUrl: 'https://placehold.co/800x300.png',
    dataAiHint: 'student studying computer',
    relevantColleges: ['iit-bombay', 'iit-delhi', 'iisc-bangalore', 'iit-madras', 'iit-kanpur', 'iit-kharagpur', 'iit-roorkee', 'iit-guwahati', 'nit-trichy', 'nit-warangal', 'jadavpur-university', 'anna-university'] // Added some top non-IITs where GATE is relevant
  },
  {
    id: 'viteee',
    name: 'VITEEE 2025',
    date: 'April 2025 (Tentative)',
    description: 'Vellore Institute of Technology Engineering Entrance Examination for admission to B.Tech programmes.',
    bannerImageUrl: 'https://placehold.co/800x300.png',
    dataAiHint: 'exam paper check',
    relevantColleges: ['vit-vellore']
  },
  {
    id: 'tancet',
    name: 'TANCET 2025 (MCA)',
    date: 'March 2025 (Tentative)',
    description: 'Tamil Nadu Common Entrance Test for admission to M.B.A., M.C.A. & M.E./M.Tech./M.Arch./M.Plan. degree programmes offered at University Departments, Constituent colleges of Anna University, Annamalai University and Government & Government Aided Colleges in Tamil Nadu.',
    bannerImageUrl: 'https://placehold.co/800x300.png',
    dataAiHint: 'exam results',
    relevantColleges: ['anna-university', 'nit-trichy', 'vit-vellore'] // Colleges in TN that accept TANCET for MCA
  },
  {
    id: 'nimcet',
    name: 'NIMCET 2025',
    date: 'June 2025 (Tentative)',
    description: 'NIT MCA Common Entrance Test, a National Level Test for admission into Master of Computer Applications programme in participating NITs.',
    bannerImageUrl: 'https://placehold.co/800x300.png',
    dataAiHint: 'computer lab exam',
    relevantColleges: ['nit-trichy', 'nit-warangal', 'nit-surathkal', 'nit-calicut', 'mnnit-allahabad', 'nit-kurukshetra', 'nit-rourkela', 'nit-jaipur', 'nit-bhopal', 'nit-jalandhar', 'nit-durgapur', 'nit-patna'] // Many NITs offering MCA
  }
];

export const getCollegeById = (id: string): College | undefined => colleges.find(c => c.id === id);
export const getExamById = (id: string): EntranceExam | undefined => entranceExams.find(e => e.id === id);

    

    